# Generated by Django 3.1.4 on 2022-03-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='product_image',
            field=models.ImageField(default='hello', upload_to='productImage'),
            preserve_default=False,
        ),
    ]
